# Form implementation generated from reading ui file '.\define_faves_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QWidget, QLabel
from PyQt6.QtCore import Qt, QMimeData
from PyQt6.QtGui import QDrag


class Ui_WorkOutList(object):
    def setupUi(self, WorkOutList):
        WorkOutList.setObjectName("WorkOutList")
        WorkOutList.resize(566, 798)
        self.widget = QtWidgets.QWidget(parent=WorkOutList)
        self.widget.setGeometry(QtCore.QRect(15, 30, 520, 751))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.all_wo_lbl = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.all_wo_lbl.setFont(font)
        self.all_wo_lbl.setObjectName("all_wo_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.all_wo_lbl)

        self.fav_wo_lbl = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fav_wo_lbl.setFont(font)
        self.fav_wo_lbl.setObjectName("fav_wo_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fav_wo_lbl)

        self.all_wo_list = QtWidgets.QListWidget(parent=self.widget)
        self.all_wo_list.setObjectName("all_wo_list")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.all_wo_list)

        item = QtWidgets.QListWidgetItem()
        self.all_wo_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.all_wo_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.all_wo_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.all_wo_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.all_wo_list.addItem(item)

        self.fav_wo_list = QtWidgets.QListWidget(parent=self.widget)
        self.fav_wo_list.setObjectName("fav_wo_list")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fav_wo_list)

        self.retranslateUi(WorkOutList)
        QtCore.QMetaObject.connectSlotsByName(WorkOutList)

    def retranslateUi(self, WorkOutList):
        _translate = QtCore.QCoreApplication.translate
        WorkOutList.setWindowTitle(_translate("WorkOutList", "Form"))
        self.all_wo_lbl.setText(_translate("WorkOutList", "Define Favorite Workouts:"))

        item = self.all_wo_list.item(0)
        item.setText(_translate("WorkOutList", "Overhead Press"))
        item = self.all_wo_list.item(1)
        item.setText(_translate("WorkOutList", "Hammer Curls"))
        item = self.all_wo_list.item(2)
        item.setText(_translate("WorkOutList", "Leg Press"))
        item = self.all_wo_list.item(3)
        item.setText(_translate("WorkOutList", "Back Extensions"))
        item = self.all_wo_list.item(4)
        item.setText(_translate("WorkOutList", "Skull Crushers"))

        self.fav_wo_lbl.setText(_translate("WorkOutList", "Your Workouts:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WorkOutList = QtWidgets.QWidget()
    ui = Ui_WorkOutList()
    ui.setupUi(WorkOutList)
    WorkOutList.show()
    sys.exit(app.exec())
